---

- name: restart rsyslog
  service: name=rsyslog state=restarted enabled=yes

- name: restart syslog-ng
  service: name=syslog-ng state=restarted enabled=yes

- name: restart ntpdate
  service: name=ntpdate.service state=restarted enabled=yes

- name: restart ntpd
  service: name=ntpdate.service state=restarted enabled=yes
  when: ansible_os_family | lower == 'redhat'

- name: restart openntpd
  service: name=openntpd.service state=restarted enabled=yes
  when: ansible_os_family | lower == 'debian'

- name: restart htpdate
  service: name=htpdate.service state=restarted enabled=yes

- name: reload systemd
  systemd: daemon_reload=yes

- name: restart journald
  service: name=systemd-journald state=restarted enabled=yes
